In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# advance pythob(libraries)

# numpy

In [1]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
        # print(i)
    # print(i)
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

enter any number: 78


1560
1521
39
39


In [ ]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

In [1]:
# wap to calculate the special char ,char ,symbol and int in the given input. 
# Program to count characters, digits, and special characters in a string

text = input("Enter a string: ")

letters = 0
digits = 0
special_chars = 0

for ch in text:
    if ch.isalpha():        
        letters += 1
    elif ch.isdigit():      
        digits += 1
    else:                   
        special_chars += 1

print("Letters:", letters)
print("Digits:", digits)
print("Special Characters / Symbols:", special_chars)


Enter a string:   


Letters: 0
Digits: 0
Special Characters / Symbols: 1


In [2]:
import numpy as np 
import time
a=[1,2,3,4]
print(type(a))
b=np.array([1,2,3,4])
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
import numpy as np 
import time
size=100000


In [3]:
arr=np.array([3,5,2,8,2,9,10,44,23,34,1])
print(arr)
np.sort(arr)

[ 3  5  2  8  2  9 10 44 23 34  1]


array([ 1,  2,  2,  3,  5,  8,  9, 10, 23, 34, 44])

In [5]:
arr=np.array([3,5,2,8,2,9,10,34,1])
np.sort(arr)
print(arr.dtype)

int32


In [9]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f")
# np.sort(arr)
print(arr.dtype)

float32


In [10]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="c")
# np.sort(arr)
print(arr.dtype)

|S1


In [11]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f2")
# np.sort(arr)
print(arr.dtype)

float16


In [13]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f4")
# np.sort(arr)
print(arr.dtype)

float32


In [14]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f5")
# np.sort(arr)
print(arr.dtype)

TypeError: data type 'f5' not understood

In [17]:
n=int(input("enter row cout:"))
i=1
while(i<=n): 
    print(' '*(n-i),'* '*i) 
    i+=1

enter row cout: 5


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [ ]:
n=int(input("enter row count:"))
for i in range(n):
    for j in range(n-i-1): 
        print(' ',end=)

In [10]:
import numpy as np
np.random.randint(0,4) 

1

In [20]:
# np.random.randint(0,10)
x=[np.random.randint(0,10)]
print(x)




[3]


In [2]:
import numpy as np
l=[] 
for i in range(1,5):
    x=int(input("enter no.:"))
    l.append(x)
print(np.array(l))
d=np.array(l)
print(type(d))

enter no.: 1
enter no.: 2
enter no.: 3
enter no.: 4


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr1=np.eye(3)



In [3]:
import numpy as np
y=np.array([1,2,3,4,5])
print(y)
print(type(y))
y[0]=10
print(y)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[10  2  3  4  5]


In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [4]:
%pip install --upgrade numpy




Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
print(np.__version__)


1.26.4


In [1]:
import numpy as np
print(np.__version__)


2.3.1


In [1]:
pip install --upgrade pandas


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 8.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.0 MB 7.4 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 7.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/11.0 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.0 MB 4.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    

In [2]:
import pandas as pd
print(pd.__version__)


2.3.1
