In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# advance pythob(libraries)

# numpy

In [1]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
        # print(i)
    # print(i)
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

enter any number: 78


1560
1521
39
39


In [ ]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

In [1]:
# wap to calculate the special char ,char ,symbol and int in the given input. 
# Program to count characters, digits, and special characters in a string

text = input("Enter a string: ")

letters = 0
digits = 0
special_chars = 0

for ch in text:
    if ch.isalpha():        
        letters += 1
    elif ch.isdigit():      
        digits += 1
    else:                   
        special_chars += 1

print("Letters:", letters)
print("Digits:", digits)
print("Special Characters / Symbols:", special_chars)


Enter a string:   


Letters: 0
Digits: 0
Special Characters / Symbols: 1


In [2]:
import numpy as np 
import time
a=[1,2,3,4]
print(type(a))
b=np.array([1,2,3,4])
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
import numpy as np 
import time
size=100000


In [3]:
arr=np.array([3,5,2,8,2,9,10,44,23,34,1])
print(arr)
np.sort(arr)

[ 3  5  2  8  2  9 10 44 23 34  1]


array([ 1,  2,  2,  3,  5,  8,  9, 10, 23, 34, 44])

In [5]:
arr=np.array([3,5,2,8,2,9,10,34,1])
np.sort(arr)
print(arr.dtype)

int32


In [9]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f")
# np.sort(arr)
print(arr.dtype)

float32


In [10]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="c")
# np.sort(arr)
print(arr.dtype)

|S1


In [11]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f2")
# np.sort(arr)
print(arr.dtype)

float16


In [13]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f4")
# np.sort(arr)
print(arr.dtype)

float32


In [2]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f5")
# np.sort(arr)
print(arr.dtype)

NameError: name 'np' is not defined

In [17]:
n=int(input("enter row cout:"))
i=1
while(i<=n): 
    print(' '*(n-i),'* '*i) 
    i+=1

enter row cout: 5


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [2]:
n=int(input("enter row count:"))
for i in range(n):
    for j in range(n-i-1): 
        print(' ',end='=')

enter row count: 5


 = = = = = = = = = =

In [10]:
import numpy as np
np.random.randint(0,4) 

1

In [20]:
# np.random.randint(0,10)
x=[np.random.randint(0,10)]
print(x)




[3]


In [2]:
import numpy as np
l=[] 
for i in range(1,5):
    x=int(input("enter no.:"))
    l.append(x)
print(np.array(l))
d=np.array(l)
print(type(d))

enter no.: 1
enter no.: 2
enter no.: 3
enter no.: 4


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr1=np.eye(3)



In [3]:
import numpy as np
y=np.array([1,2,3,4,5])
print(y)
print(type(y))
y[0]=10
print(y)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[10  2  3  4  5]


In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [4]:
%pip install --upgrade numpy




Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
print(np.__version__)


1.26.4


In [1]:
import numpy as np
print(np.__version__)


2.3.1


In [1]:
pip install --upgrade pandas


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 8.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.0 MB 7.4 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 7.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/11.0 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.0 MB 4.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    

In [2]:
import pandas as pd
print(pd.__version__)


2.3.1


In [3]:
n=int(input("enter row cout:"))
i=1
while(i<=n): 
    print(' '*i,'* '*(n-i)) 
    i+=1

enter row cout: 6


  * * * * * 
   * * * * 
    * * * 
     * * 
      * 
       


In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
y=[1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

739 ns ± 59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
import numpy as np
%timeit np.arange(1,9)**4

2.06 μs ± 130 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array--------

In [13]:
x=[1,2,3,4,5]
y=np.array(x)
y
# print(y) 

array([1, 2, 3, 4, 5])

In [16]:
l=[] 
for i in range(1,5): 
    int_1=int(input("enter any number:"))
    l.append(int_1)
print(np.array(l)) 
%timeit np.arange(1,5)**4

enter any number: 1
enter any number: 2
enter any number: 3
enter any number: 4


[1 2 3 4]
6.8 μs ± 594 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
ar_2=np.array([[1,2,3,4],[5,4,3,2]])
print(ar_2)
print(ar_2.ndim)

[[1 2 3 4]
 [5 4 3 2]]
2


In [19]:
ar_3=np.array([[[0,1,2,3,4],[8,7,6,5,4],[4,5,6,7,8]]])
print(ar_3)
print(ar_3.ndim)

[[[0 1 2 3 4]
  [8 7 6 5 4]
  [4 5 6 7 8]]]
3


In [21]:
ar_n=np.array([3,4,5,6],ndmin=10)
print(ar_n)
print(ar_n.ndim)

[[[[[[[[[[3 4 5 6]]]]]]]]]]
10


# Create numpy array using numpy functions

In [25]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print(ar_zero.ndim)
print(ar_zero1)
print(ar_zero1.ndim)

[0. 0. 0. 0.]
1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [28]:
ar_one=np.ones(4)
print(ar_one)
print(ar_one.ndim)
ar_one1=np.ones((2,3))
print(ar_one1)
print(ar_zero1.ndim)

[1. 1. 1. 1.]
1
[[1. 1. 1.]
 [1. 1. 1.]]
2


In [29]:
ar_emp=np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


In [31]:
ar_rg=np.arange(4)
print(ar_rg)
print(ar_rg.ndim)

[0 1 2 3]
1


In [33]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np
ar_dia1=np.eye(3,5)
print(ar_dia1)
print(ar_dia1.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
2


In [3]:
ar_lins=np.linspace(0,20,num=5)
print(ar_lins)
print(ar_lins.ndim)

[ 0.  5. 10. 15. 20.]
1


# create numpy arrays with random numbers

# Random:---------------

In [7]:
import numpy as np
var=np.random.rand(4)
print(var)
var1=np.random.rand(2,5)
print(var1)

[0.01153764 0.79883462 0.80971911 0.41891682]
[[0.94637751 0.33394397 0.45066088 0.05814811 0.7451466 ]
 [0.63814332 0.15402776 0.78870219 0.64243647 0.28822573]]


In [3]:
import numpy as np
var2=np.random.randn(5)
print(var2)

[-0.91782517  0.6001806   0.20504295  0.81067595  0.20013386]


In [6]:
var3=np.random.ranf(5)
print(var3)

[0.41644422 0.14660074 0.7869724  0.54372245 0.63311573]


In [ ]:
d.randint(min,max,total_value)

In [34]:
var4=np.random.randint(4,20,10)
print(var4)

[ 4 13 15 11 18  8  5 14  7 17]


# data type in numpy arrays

In [35]:
conda install numpy<2


error: incomplete escape \U at position 28