In [1]:
import numpy as np 

In [2]:
a=np.array([1,2,3,4,5,6,7])

In [4]:
print(a)
print(type(a))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
a=np.random.random((3,3))
a=np.round(a*100)
a.astype(np.int64)

array([[53, 61, 67],
       [29, 95, 24],
       [98, 55, 96]])

In [4]:
np.max(a,axis=0) #max no. in columns.

array([98., 95., 96.])

In [7]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [8]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4) 
a3=np.arange(8).reshape(2,2,2)