In [1]:
import numpy as np 

In [2]:
a=np.array([1,2,3,4,5,6,7])

In [4]:
print(a)
print(type(a))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
a=np.random.random((3,3))
a=np.round(a*100)
a.astype(np.int64)

array([[53, 61, 67],
       [29, 95, 24],
       [98, 55, 96]])

In [4]:
np.max(a,axis=0) #max no. in columns.

array([98., 95., 96.])

In [7]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### Indexing

In [2]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4) 
a3=np.arange(8).reshape(2,2,2)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a2[1,2]

np.int64(6)

In [5]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
print(a3[1,0,1])

5


In [9]:
a3[0,0,1]

np.int64(1)

In [10]:
print(a3[0,0,0])

0


In [31]:
a4=np.arange(16).reshape(2,2,2,2)

In [32]:
a4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [34]:
print(a4[1,1,1,1])

15


In [35]:
print(a4[1,0,0,1])

9


In [36]:
print(a4[1,1,0,1])

13


In [44]:
a5=np.arange(32).reshape(2,2,2,2,2)

In [45]:
a5

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [46]:
print(a5[1,1,1,0,1])

29


In [21]:
s4=np.random.random((2,3))
s4=np.round(s4*100)
s4=s4.astype(np.int64)

In [22]:
s4

array([[73, 89, 89],
       [18, 48, 81]])

### Slicing

In [47]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[2:6:1]

array([2, 3, 4, 5])

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[0,:]

array([0, 1, 2, 3])

In [56]:
a2[:,2]

array([ 2,  6, 10])

In [57]:
a2[:,3]

array([ 3,  7, 11])

In [59]:
a2[1,:]

array([4, 5, 6, 7])

In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [64]:
a2[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [65]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [71]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [72]:
a2[0:,0::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [69]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
a3[0:,1:,0:]

array([[[2, 3]],

       [[6, 7]]])

In [73]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [74]:
a3=np.arange(27).reshape(3,3,3)

In [75]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
a3[1,0::2,0::2]

array([[ 9, 11],
       [15, 17]])

In [78]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
a3[0,1,0:]

array([3, 4, 5])

In [82]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [83]:
for i in a1: 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [85]:
for i in a2: 
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [86]:
for i in a3: 
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [87]:
for i in np.nditer(a3): #first change in 1D then print
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping 
* reshape
* transpose
* revel

In [89]:
# transpose 
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [91]:
# ravel 
a3.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking
* Horizontal Stacking
* Vertical Stacking

In [95]:
# Horizontal Stacking 
h1=np.arange(12).reshape(3,4)
h2=np.arange(12,24).reshape(3,4)
print(h1)
print(h2)
np.hstack((h1,h2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [97]:
print(h1)
print(h2)
np.vstack((h1,h2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

 ### Splitting
 * Horizontal Splitting
 * Vertical Splitting

In [101]:
# Horizontal Splitting 
print(h1)
np.hsplit(h1,2) #must be equal division

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [103]:
# Vertical Stacking 
print(h1)
# np.vsplit(h1,2) #must be equal division 
np.vsplit(h1,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]