# Numpy Tricks

### np.sort
np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [25]:
import numpy as np 
a=np.random.randint(1,100,15)
a1=np.random.randint(1,100,24).reshape(6,4)
print(a) 
print(a1)

[58 35 17 69 58 43 65 31 98  7 17 14 68 64 13]
[[36 49 35 59]
 [18 54 80 85]
 [13 64 85 21]
 [57 82 74 20]
 [65 27 82 10]
 [85 42  1 59]]


In [30]:
np.sort(a1)
a1

array([[36, 49, 35, 59],
       [18, 54, 80, 85],
       [13, 64, 85, 21],
       [57, 82, 74, 20],
       [65, 27, 82, 10],
       [85, 42,  1, 59]], dtype=int32)

In [37]:
# print(np.sort(a1,axis=1))
print(np.sort(a1,axis=0)[::-1])
np.sort(a1,axis=1)[::-1]

[[85 82 85 85]
 [65 64 82 59]
 [57 54 80 59]
 [36 49 74 21]
 [18 42 35 20]
 [13 27  1 10]]


array([[ 1, 42, 59, 85],
       [10, 27, 65, 82],
       [20, 57, 74, 82],
       [13, 21, 64, 85],
       [18, 54, 80, 85],
       [35, 36, 49, 59]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [42]:
# append value in 1D array. 
np.append(a1,200)


array([ 36,  49,  35,  59,  18,  54,  80,  85,  13,  64,  85,  21,  57,
        82,  74,  20,  65,  27,  82,  10,  85,  42,   1,  59, 200])

In [48]:
# append value in 2D array. 
np.append(a1,np.ones((a1.shape[0],1)),axis=1)

array([[36., 49., 35., 59.,  1.],
       [18., 54., 80., 85.,  1.],
       [13., 64., 85., 21.,  1.],
       [57., 82., 74., 20.,  1.],
       [65., 27., 82., 10.,  1.],
       [85., 42.,  1., 59.,  1.]])

In [ ]:
np.ones()

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [2]:
import numpy as np 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)
np.concatenate((c,d),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [4]:
e=np.array([1,2,3,1,2,3,4,5,3,6,6,4])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [5]:
e

array([1, 2, 3, 1, 2, 3, 4, 5, 3, 6, 6, 4])

In [9]:
np.expand_dims(e,axis=0).shape

(1, 12)

In [8]:
np.expand_dims(e,axis=1).shape

(12, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [12]:
# find all indices with values greater than 50
a=np.array([5,53,24,55,13,96,47,96,34,98,33,24,75,34,67,53,23,54,46,87,54,86])
np.where(a>50)

(array([ 1,  3,  5,  7,  9, 12, 14, 15, 17, 19, 20, 21]),)

In [13]:
# replace all values > 50 with 0 
# np.where(condition,true,false) 
np.where(a>50,0,a)

array([ 5,  0, 24,  0, 13,  0, 47,  0, 34,  0, 33, 24,  0, 34,  0,  0, 23,
        0, 46,  0,  0,  0])

In [14]:
#here, all even no. become 0 and odd no. as it is 
np.where(a%2==0,0,a)

array([ 5, 53,  0, 55, 13,  0, 47,  0,  0,  0, 33,  0, 75,  0, 67, 53, 23,
        0,  0, 87,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [17]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [20]:
np.argmax(a)

np.int64(9)

In [21]:
# for 2D  
c

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
# 0 colunms wise of 1 row wise
np.argmax(c,axis=0)

array([1, 1, 1])

In [24]:
np.argmin(a)

np.int64(0)

In [25]:
# np.argmin()
np.argmin(c,axis=0)

array([0, 0, 0])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [27]:
np.cumsum(a)

array([   5,   58,   82,  137,  150,  246,  293,  389,  423,  521,  554,
        578,  653,  687,  754,  807,  830,  884,  930, 1017, 1071, 1157])

In [29]:
print(c)
np.cumsum(c)

[[0 1 2]
 [3 4 5]]


array([ 0,  1,  3,  6, 10, 15])

In [30]:
# np.cumprod() 
np.cumprod(a)

array([                   5,                  265,                 6360,
                     349800,              4547400,            436550400,
                20517868800,        1969715404800,       66970323763200,
           6563091728793600,   216582027050188800,  5197968649204531200,
        2466023142439256064, -8388933525613051904, -8656224004787929088,
        2388729588978548736,  -399451674622033920, -3123646355880280064,
        3886220219183529984,  6059765742195179520, -4814043248232235008,
       -8179349726362075136])