# Numpy Tricks

### np.sort
np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [25]:
import numpy as np 
a=np.random.randint(1,100,15)
a1=np.random.randint(1,100,24).reshape(6,4)
print(a) 
print(a1)

[58 35 17 69 58 43 65 31 98  7 17 14 68 64 13]
[[36 49 35 59]
 [18 54 80 85]
 [13 64 85 21]
 [57 82 74 20]
 [65 27 82 10]
 [85 42  1 59]]


In [30]:
np.sort(a1)
a1

array([[36, 49, 35, 59],
       [18, 54, 80, 85],
       [13, 64, 85, 21],
       [57, 82, 74, 20],
       [65, 27, 82, 10],
       [85, 42,  1, 59]], dtype=int32)

In [37]:
# print(np.sort(a1,axis=1))
print(np.sort(a1,axis=0)[::-1])
np.sort(a1,axis=1)[::-1]

[[85 82 85 85]
 [65 64 82 59]
 [57 54 80 59]
 [36 49 74 21]
 [18 42 35 20]
 [13 27  1 10]]


array([[ 1, 42, 59, 85],
       [10, 27, 65, 82],
       [20, 57, 74, 82],
       [13, 21, 64, 85],
       [18, 54, 80, 85],
       [35, 36, 49, 59]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [42]:
# append value in 1D array. 
np.append(a1,200)


array([ 36,  49,  35,  59,  18,  54,  80,  85,  13,  64,  85,  21,  57,
        82,  74,  20,  65,  27,  82,  10,  85,  42,   1,  59, 200])

In [48]:
# append value in 2D array. 
np.append(a1,np.ones((a1.shape[0],1)),axis=1)

array([[36., 49., 35., 59.,  1.],
       [18., 54., 80., 85.,  1.],
       [13., 64., 85., 21.,  1.],
       [57., 82., 74., 20.,  1.],
       [65., 27., 82., 10.,  1.],
       [85., 42.,  1., 59.,  1.]])

In [ ]:
np.ones()

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [2]:
import numpy as np 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
