# Numpy Tricks

### np.sort
np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np 
a=np.random.randint(1,100,15)
a1=np.random.randint(1,100,24).reshape(6,4)
print(a) 
print(a1)

[32 42 68  5 32 79 57 53 45 22 73  2 42 11 29]
[[85  1 66 70]
 [22 18 34 38]
 [53 66 40 71]
 [21 54 61 84]
 [87 53 11 31]
 [43 56 90 81]]


In [2]:
np.sort(a1)
a1

array([[85,  1, 66, 70],
       [22, 18, 34, 38],
       [53, 66, 40, 71],
       [21, 54, 61, 84],
       [87, 53, 11, 31],
       [43, 56, 90, 81]], dtype=int32)

In [3]:
# print(np.sort(a1,axis=1))
print(np.sort(a1,axis=0)[::-1])
np.sort(a1,axis=1)[::-1]

[[87 66 90 84]
 [85 56 66 81]
 [53 54 61 71]
 [43 53 40 70]
 [22 18 34 38]
 [21  1 11 31]]


array([[43, 56, 81, 90],
       [11, 31, 53, 87],
       [21, 54, 61, 84],
       [40, 53, 66, 71],
       [18, 22, 34, 38],
       [ 1, 66, 70, 85]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [4]:
# append value in 1D array. 
np.append(a1,200)


array([ 85,   1,  66,  70,  22,  18,  34,  38,  53,  66,  40,  71,  21,
        54,  61,  84,  87,  53,  11,  31,  43,  56,  90,  81, 200])

In [5]:
# append value in 2D array. 
np.append(a1,np.ones((a1.shape[0],1)),axis=1)

array([[85.,  1., 66., 70.,  1.],
       [22., 18., 34., 38.,  1.],
       [53., 66., 40., 71.,  1.],
       [21., 54., 61., 84.,  1.],
       [87., 53., 11., 31.,  1.],
       [43., 56., 90., 81.,  1.]])

In [6]:
# np.ones()

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
import numpy as np 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)
np.concatenate((c,d),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [9]:
e=np.array([1,2,3,1,2,3,4,5,3,6,6,4])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [10]:
e

array([1, 2, 3, 1, 2, 3, 4, 5, 3, 6, 6, 4])

In [11]:
np.expand_dims(e,axis=0).shape

(1, 12)

In [12]:
np.expand_dims(e,axis=1).shape

(12, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [13]:
# find all indices with values greater than 50
a=np.array([5,53,24,55,13,96,47,96,34,98,33,24,75,34,67,53,23,54,46,87,54,86])
np.where(a>50)

(array([ 1,  3,  5,  7,  9, 12, 14, 15, 17, 19, 20, 21]),)

In [14]:
# replace all values > 50 with 0 
# np.where(condition,true,false) 
np.where(a>50,0,a)

array([ 5,  0, 24,  0, 13,  0, 47,  0, 34,  0, 33, 24,  0, 34,  0,  0, 23,
        0, 46,  0,  0,  0])

In [15]:
#here, all even no. become 0 and odd no. as it is 
np.where(a%2==0,0,a)

array([ 5, 53,  0, 55, 13,  0, 47,  0,  0,  0, 33,  0, 75,  0, 67, 53, 23,
        0,  0, 87,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [16]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [17]:
np.argmax(a)

np.int64(9)

In [18]:
# for 2D  
c

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
# 0 colunms wise of 1 row wise
np.argmax(c,axis=0)

array([1, 1, 1])

In [20]:
np.argmin(a)

np.int64(0)

In [21]:
# np.argmin()
np.argmin(c,axis=0)

array([0, 0, 0])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [22]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [23]:
np.cumsum(a)

array([   5,   58,   82,  137,  150,  246,  293,  389,  423,  521,  554,
        578,  653,  687,  754,  807,  830,  884,  930, 1017, 1071, 1157])

In [24]:
print(c)
np.cumsum(c)

[[0 1 2]
 [3 4 5]]


array([ 0,  1,  3,  6, 10, 15])

In [25]:
# np.cumprod() 
np.cumprod(a)

array([                   5,                  265,                 6360,
                     349800,              4547400,            436550400,
                20517868800,        1969715404800,       66970323763200,
           6563091728793600,   216582027050188800,  5197968649204531200,
        2466023142439256064, -8388933525613051904, -8656224004787929088,
        2388729588978548736,  -399451674622033920, -3123646355880280064,
        3886220219183529984,  6059765742195179520, -4814043248232235008,
       -8179349726362075136])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [26]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [27]:
np.percentile(a,50)

np.float64(53.0)

In [28]:
np.percentile(a,100)

np.float64(98.0)

In [29]:
np.median(a)

np.float64(53.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [30]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 3, 3, 2, 5, 1, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [31]:
salary=np.array([12000,18000,20000,24000,30000])
experince=np.array([1,2,3,4,5])
np.corrcoef(salary,experince)

array([[1.        , 0.98775691],
       [0.98775691, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [32]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [33]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [34]:
a

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [35]:
np.flip(a)

array([86, 54, 87, 46, 54, 23, 53, 67, 34, 75, 24, 33, 98, 34, 96, 47, 96,
       13, 55, 24, 53,  5])

In [36]:
np.flip(c,axis=1)

array([[2, 1, 0],
       [5, 4, 3]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [37]:
a 

array([ 5, 53, 24, 55, 13, 96, 47, 96, 34, 98, 33, 24, 75, 34, 67, 53, 23,
       54, 46, 87, 54, 86])

In [38]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [39]:
a

array([110, 530,  24,  55,  13,  96,  47,  96,  34,  98,  33,  24,  75,
        34,  67,  53,  23,  54,  46,  87,  54,  86])

In [40]:
np.delete(a,[0,2,4])

array([530,  55,  96,  47,  96,  34,  98,  33,  24,  75,  34,  67,  53,
        23,  54,  46,  87,  54,  86])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [41]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
np.setdiff1d(n,m)

array([6, 7])

In [43]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [44]:
m[np.in1d(m,1)]

C:\Users\sawsu\AppData\Local\Temp\ipykernel_12488\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [45]:
a

array([110, 530,  24,  55,  13,  96,  47,  96,  34,  98,  33,  24,  75,
        34,  67,  53,  23,  54,  46,  87,  54,  86])

In [46]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 55, 25, 75, 47, 75, 34, 75, 33, 25, 75, 34, 67, 53, 25,
       54, 46, 75, 54, 75])