In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# advance pythob(libraries)

# numpy

In [1]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
        # print(i)
    # print(i)
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

enter any number: 78


1560
1521
39
39


In [ ]:
# wap to find the sum and count of first n even and an odd numbers... 
n=int(input("enter any number:"))
sum_e=0
sum_o=0
count_e=0
count_o=0
for i in range(1,n+1):
    if i%2==0: 
        sum_e=sum_e+i
        count_e=count_e+1
    else: 
        sum_o=sum_o+i
        count_o=count_o+1
print(sum_e)
print(sum_o)
print(count_e)
print(count_e)

In [1]:
# wap to calculate the special char ,char ,symbol and int in the given input. 
# Program to count characters, digits, and special characters in a string

text = input("Enter a string: ")

letters = 0
digits = 0
special_chars = 0

for ch in text:
    if ch.isalpha():        
        letters += 1
    elif ch.isdigit():      
        digits += 1
    else:                   
        special_chars += 1

print("Letters:", letters)
print("Digits:", digits)
print("Special Characters / Symbols:", special_chars)


Enter a string:   


Letters: 0
Digits: 0
Special Characters / Symbols: 1


In [2]:
import numpy as np 
import time
a=[1,2,3,4]
print(type(a))
b=np.array([1,2,3,4])
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
import numpy as np 
import time
size=100000


In [3]:
arr=np.array([3,5,2,8,2,9,10,44,23,34,1])
print(arr)
np.sort(arr)

[ 3  5  2  8  2  9 10 44 23 34  1]


array([ 1,  2,  2,  3,  5,  8,  9, 10, 23, 34, 44])

In [5]:
arr=np.array([3,5,2,8,2,9,10,34,1])
np.sort(arr)
print(arr.dtype)

int32


In [9]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f")
# np.sort(arr)
print(arr.dtype)

float32


In [10]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="c")
# np.sort(arr)
print(arr.dtype)

|S1


In [11]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f2")
# np.sort(arr)
print(arr.dtype)

float16


In [13]:
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f4")
# np.sort(arr)
print(arr.dtype)

float32


In [2]:
import numpy as np
arr=np.array([3,5,2,8,2,9,10,34,1],dtype="f5")
# np.sort(arr)
print(arr.dtype)

TypeError: data type 'f5' not understood

In [17]:
n=int(input("enter row cout:"))
i=1
while(i<=n): 
    print(' '*(n-i),'* '*i) 
    i+=1

enter row cout: 5


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [2]:
n=int(input("enter row count:"))
for i in range(n):
    for j in range(n-i-1): 
        print(' ',end='=')

enter row count: 5


 = = = = = = = = = =

In [10]:
import numpy as np
np.random.randint(0,4) 

1

In [20]:
# np.random.randint(0,10)
x=[np.random.randint(0,10)]
print(x)




[3]


In [2]:
import numpy as np
l=[] 
for i in range(1,5):
    x=int(input("enter no.:"))
    l.append(x)
print(np.array(l))
d=np.array(l)
print(type(d))

enter no.: 1
enter no.: 2
enter no.: 3
enter no.: 4


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr1=np.eye(3)



In [3]:
import numpy as np
y=np.array([1,2,3,4,5])
print(y)
print(type(y))
y[0]=10
print(y)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[10  2  3  4  5]


In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [4]:
%pip install --upgrade numpy




Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
print(np.__version__)


1.26.4


In [1]:
import numpy as np
print(np.__version__)


2.3.1


In [1]:
pip install --upgrade pandas


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 8.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.0 MB 7.4 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 7.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/11.0 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 5.2 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.0 MB 4.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.0 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    

In [2]:
import pandas as pd
print(pd.__version__)


2.3.1


In [3]:
n=int(input("enter row cout:"))
i=1
while(i<=n): 
    print(' '*i,'* '*(n-i)) 
    i+=1

enter row cout: 6


  * * * * * 
   * * * * 
    * * * 
     * * 
      * 
       


In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
y=[1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

739 ns ± 59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
import numpy as np
%timeit np.arange(1,9)**4

2.06 μs ± 130 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array--------

In [13]:
x=[1,2,3,4,5]
y=np.array(x)
y
# print(y) 

array([1, 2, 3, 4, 5])

In [16]:
l=[] 
for i in range(1,5): 
    int_1=int(input("enter any number:"))
    l.append(int_1)
print(np.array(l)) 
%timeit np.arange(1,5)**4

enter any number: 1
enter any number: 2
enter any number: 3
enter any number: 4


[1 2 3 4]
6.8 μs ± 594 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
ar_2=np.array([[1,2,3,4],[5,4,3,2]])
print(ar_2)
print(ar_2.ndim)

[[1 2 3 4]
 [5 4 3 2]]
2


In [19]:
ar_3=np.array([[[0,1,2,3,4],[8,7,6,5,4],[4,5,6,7,8]]])
print(ar_3)
print(ar_3.ndim)

[[[0 1 2 3 4]
  [8 7 6 5 4]
  [4 5 6 7 8]]]
3


In [21]:
ar_n=np.array([3,4,5,6],ndmin=10)
print(ar_n)
print(ar_n.ndim)

[[[[[[[[[[3 4 5 6]]]]]]]]]]
10


# Create numpy array using numpy functions

In [25]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print(ar_zero.ndim)
print(ar_zero1)
print(ar_zero1.ndim)

[0. 0. 0. 0.]
1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [28]:
ar_one=np.ones(4)
print(ar_one)
print(ar_one.ndim)
ar_one1=np.ones((2,3))
print(ar_one1)
print(ar_zero1.ndim)

[1. 1. 1. 1.]
1
[[1. 1. 1.]
 [1. 1. 1.]]
2


In [29]:
ar_emp=np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


In [31]:
ar_rg=np.arange(4)
print(ar_rg)
print(ar_rg.ndim)

[0 1 2 3]
1


In [33]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np
ar_dia1=np.eye(3,5)
print(ar_dia1)
print(ar_dia1.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
2


In [3]:
ar_lins=np.linspace(0,20,num=5)
print(ar_lins)
print(ar_lins.ndim)

[ 0.  5. 10. 15. 20.]
1


# create numpy arrays with random numbers

# Random:---------------

In [7]:
import numpy as np
var=np.random.rand(4)
print(var)
var1=np.random.rand(2,5)
print(var1)

[0.01153764 0.79883462 0.80971911 0.41891682]
[[0.94637751 0.33394397 0.45066088 0.05814811 0.7451466 ]
 [0.63814332 0.15402776 0.78870219 0.64243647 0.28822573]]


In [3]:
import numpy as np
var2=np.random.randn(5)
print(var2)

[-0.91782517  0.6001806   0.20504295  0.81067595  0.20013386]


In [6]:
var3=np.random.ranf(5)
print(var3)

[0.41644422 0.14660074 0.7869724  0.54372245 0.63311573]


In [ ]:
d.randint(min,max,total_value)

In [34]:
var4=np.random.randint(4,20,10)
print(var4)

[ 4 13 15 11 18  8  5 14  7 17]


# data type in numpy arrays

In [6]:
import numpy as np
var_a=np.array([1,2,3,4,5])
print("data_type:",var_a.dtype)

data_type: int64


In [9]:
import numpy as np
# change the data types
var_a=np.array([1,2,3,4,5],dtype=np.int8)
print("data_type:",var_a.dtype)

data_type: int8


In [7]:
var_a=np.array(['a','b',1,2,3,4,5])
print("data_type:",var_a.dtype)

data_type: <U21


In [8]:
var_a=np.array([1.0,2.12,3.3,0.4,5])
print("data_type:",var_a.dtype)

data_type: float64


# Arithematic operation in numpy arrays

In [3]:
import numpy as np
var_ar=np.array([1,2,3,4])
var_add=var_ar+4
print(var_add)

[5 6 7 8]


In [9]:
# Addition using functions
var_ar=np.array([1,2,3,4])
var_add=np.add(var_ar,4)
print(var_add)

[5 6 7 8]


In [4]:
var_ar=np.array([1,2,3,4])
var_ar1=np.array([1,2,3,4])
var_add=var_ar+var_ar1
print(var_add)

[2 4 6 8]


In [8]:
# Addition using functions
var_ar=np.array([1,2,3,4])
var_ar1=np.array([1,2,3,4])
var_add=np.add(var_ar,var_ar1)
print(var_add)

[2 4 6 8]


In [5]:
import numpy as np
var_ar=np.array([1,2,3,4])
var_sub=var_ar-4
print(var_sub)

[-3 -2 -1  0]


In [13]:
# subtraction using functions
var_ar=np.array([1,2,3,4])
var_sub=np.subtract(var_ar,4)
print(var_sub)

[-3 -2 -1  0]


In [15]:
# subtraction using functions
var_ar=np.array([1,2,3,4])
var_ar1=np.array([1,2,3,4])
var_add=np.add(var_ar,var_ar1)
print(var_sub)

[0 0 0 0]


In [6]:
import numpy as np
var_ar=np.array([1,2,3,4])
var_div=var_ar/4
print(var_div)

[0.25 0.5  0.75 1.  ]


In [7]:
import numpy as np
var_ar=np.array([1,2,3,4])
var_mod=var_ar%4
print(var_mod)

[1 2 3 0]


In [17]:
# reciprocal function
import numpy as np
var_ar=np.array([1,2,3,4])
var_reciprocal=np.reciprocal(var_ar)
print(var_reciprocal)

[1 0 0 0]


In [18]:
# reciprocal function
import numpy as np
var_ar=np.array([1,2,3,4,0.5])
var_reciprocal=np.reciprocal(var_ar)
print(var_reciprocal)

[1.         0.5        0.33333333 0.25       2.        ]


# 2D array

In [20]:
var_2d=np.array([[1,2,3,4],[1,2,3,4]])
var_2d1=np.array([[1,2,3,4],[1,2,3,4]])
print(var_2d)
print()
print(var_2d1)
print()
var_2d_mul=var_2d*var_2d1
print(var_2d_mul)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [12]:
import pandas as pd
data={"name":['sun','moon','earth'],
'age':[22,34,33],
'city':['bhopal','indore','delhi']
}
df=pd.DataFrame(data)
df.to_excel("output.xlsx",index=False)
print(df)


    name  age    city
0    sun   22  bhopal
1   moon   34  indore
2  earth   33   delhi


In [15]:
pd.read_csv("D:/Ad_py_lib.csv/pandas_and_numpy/cars1.csv")

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0         1  chevrolet chevelle malibu         NaN          NaN          NaN   
1         1          buick skylark 320         NaN          NaN          NaN   
2         1         plymouth satellite         NaN          NaN          NaN   
3         1              amc rebel sst         NaN          NaN          NaN   
4         1                ford torino         NaN          NaN          NaN   
..      ...                        ...         ...          ...          ...   
193       1              ford maverick         NaN          NaN          NaN   
194       1                 amc hornet         NaN          NaN          NaN   
195       1         chevrolet chevette         NaN          NaN          NaN   
196       1            chevrolet woody         NaN          NaN          NaN   
197       2                  vw rabbit         NaN          NaN          NaN   

     Unnamed: 12  Unnamed: 13  
0            NaN          NaN  
1            NaN          NaN  
2            NaN          NaN  
3            NaN          NaN  
4            NaN          NaN  
..           ...          ...  
193          NaN          NaN  
194          NaN          NaN  
195          NaN          NaN  
196          NaN          NaN  
197          NaN          NaN  

[198 rows x 14 columns]

In [18]:
df=pd.read_csv("D:/Ad_py_lib.csv/pandas_and_numpy/cars1.csv")

In [19]:
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70   
1  15.0          8           350        165    3693          11.5     70   
2  18.0          8           318        150    3436          11.0     70   
3  16.0          8           304        150    3433          12.0     70   
4  17.0          8           302        140    3449          10.5     70   
5  15.0          8           429        198    4341          10.0     70   
6  14.0          8           454        220    4354           9.0     70   
7  14.0          8           440        215    4312           8.5     70   
8  14.0          8           455        225    4425          10.0     70   
9  15.0          8           390        190    3850           8.5     70   

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN   
1       1          buick skylark 320         NaN          NaN          NaN   
2       1         plymouth satellite         NaN          NaN          NaN   
3       1              amc rebel sst         NaN          NaN          NaN   
4       1                ford torino         NaN          NaN          NaN   
5       1           ford galaxie 500         NaN          NaN          NaN   
6       1           chevrolet impala         NaN          NaN          NaN   
7       1          plymouth fury iii         NaN          NaN          NaN   
8       1           pontiac catalina         NaN          NaN          NaN   
9       1         amc ambassador dpl         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN  
5          NaN          NaN  
6          NaN          NaN  
7          NaN          NaN  
8          NaN          NaN  
9          NaN          NaN

In [21]:
df.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                 car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
193       1       ford maverick         NaN          NaN          NaN   
194       1          amc hornet         NaN          NaN          NaN   
195       1  chevrolet chevette         NaN          NaN          NaN   
196       1     chevrolet woody         NaN          NaN          NaN   
197       2           vw rabbit         NaN          NaN          NaN   

     Unnamed: 12  Unnamed: 13  
193          NaN          NaN  
194          NaN          NaN  
195          NaN          NaN  
196          NaN          NaN  
197          NaN          NaN

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64  
 2   displacement  198 non-null    int64  
 3   horsepower    198 non-null    object 
 4   weight        198 non-null    int64  
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64  
 7   origin        198 non-null    int64  
 8   car           198 non-null    object 
 9   Unnamed: 9    0 non-null      float64
 10  Unnamed: 10   0 non-null      float64
 11  Unnamed: 11   0 non-null      float64
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
dtypes: float64(7), int64(5), object(2)
memory usage: 21.8+ KB


In [24]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  198.000000  198.000000    198.000000   198.000000    198.000000   
mean    19.719697    5.898990    223.469697  3177.888889     15.005556   
std      5.814254    1.785417    115.181017   934.783733      2.872382   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     15.000000    4.000000    113.250000  2302.500000     13.000000   
50%     19.000000    6.000000    228.000000  3030.000000     15.000000   
75%     24.375000    8.000000    318.000000  4080.750000     16.800000   
max     35.000000    8.000000    455.000000  5140.000000     23.500000   

            model      origin  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
count  198.000000  198.000000         0.0          0.0          0.0   
mean    72.818182    1.439394         NaN          NaN          NaN   
std      1.865332    0.708085         NaN          NaN          NaN   
min     70.000000    1.000000         NaN          NaN          NaN   
25%     71.000000    1.000000         NaN          NaN          NaN   
50%     73.000000    1.000000         NaN          NaN          NaN   
75%     74.000000    2.000000         NaN          NaN          NaN   
max     76.000000    3.000000         NaN          NaN          NaN   

       Unnamed: 12  Unnamed: 13  
count          0.0          0.0  
mean           NaN          NaN  
std            NaN          NaN  
min            NaN          NaN  
25%            NaN          NaN  
50%            NaN          NaN  
75%            NaN          NaN  
max            NaN          NaN

In [25]:
# In pandas, shape is an attribute, not a method (function).
df.shape()

TypeError: 'tuple' object is not callable

In [27]:
df.shape

(198, 14)

In [32]:
column=df['model']
print(column)

0      70
1      70
2      70
3      70
4      70
       ..
193    76
194    76
195    76
196    76
197    76
Name: model, Length: 198, dtype: int64


In [37]:
# To access single columns
colunms=df["mpg"]
print(colunms)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
193    24.0
194    22.5
195    29.0
196    24.5
197    29.0
Name: mpg, Length: 198, dtype: float64


In [41]:
filter_rows=df[(df['weight']>4000)]
print(filter_rows)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
5    15.0          8           429        198    4341          10.0     70   
6    14.0          8           454        220    4354           9.0     70   
7    14.0          8           440        215    4312           8.5     70   
8    14.0          8           455        225    4425          10.0     70   
25   10.0          8           360        215    4615          14.0     70   
26   10.0          8           307        200    4376          15.0     70   
27   11.0          8           318        210    4382          13.5     70   
28    9.0          8           304        193    4732          18.5     70   
38   14.0          8           350        165    4209          12.0     71   
39   14.0          8           400        175    4464          11.5     71   
40   14.0          8           351        153    4154          13.5     71   
41   14.0          8           318        150    4096          1

In [43]:
filter_rows_cond=df[(df['weight']<3000) & (df['model']>72)]
print(filter_rows_cond)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
99   18.0          6           232        100    2945          16.0     73   
101  23.0          6           198         95    2904          16.0     73   
102  26.0          4            97         46    1950          21.0     73   
107  18.0          6           232        100    2789          15.0     73   
108  20.0          4            97         88    2279          19.0     73   
109  21.0          4           140         72    2401          19.5     73   
110  22.0          4           108         94    2379          16.5     73   
111  18.0          3            70         90    2124          13.5     73   
112  19.0          4           122         85    2310          18.5     73   
113  21.0          6           155        107    2472          14.0     73   
114  26.0          4            98         90    2265          15.5     73   
117  29.0          4            68         49    1867          1

In [63]:
df['max_weight']=df['weight']*1.05
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8         13333        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  Unnamed: 9  Unnamed: 10

In [53]:
# adding columns
df.insert(4,'Max_weight',[1,2,3,4,5,6,7,89,7])

ValueError: Length of values (9) does not match length of index (198)

In [56]:
# updating particular columns with index no..
df.loc[0,'displacement']=13333
print(df) #show always raw text(no styling)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8         13333        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  Unnamed: 9  Unnamed: 10

In [66]:
# updationg all columns's data
df['weight']=df['weight']*1.05
print(df)

      mpg  cylinders  displacement horsepower     weight  acceleration  model  \
0    18.0          8         13333        130  3863.1600          12.0     70   
1    15.0          8           350        165  4071.5325          11.5     70   
2    18.0          8           318        150  3788.1900          11.0     70   
3    16.0          8           304        150  3784.8825          12.0     70   
4    17.0          8           302        140  3802.5225          10.5     70   
..    ...        ...           ...        ...        ...           ...    ...   
193  24.0          6           200         81  3320.7300          17.6     76   
194  22.5          6           232         90  3401.2125          17.6     76   
195  29.0          4            85         52  2243.5875          22.2     76   
196  24.5          4            98         60  2385.8100          22.1     76   
197  29.0          4            90         70  2135.5425          14.2     76   

     origin                

In [72]:
# removing columns
df.drop(columns=['model'],inplace=True)
print(df)

      mpg  cylinders  displacement horsepower  acceleration  origin  \
0    18.0          8         13333        130          12.0       1   
1    15.0          8           350        165          11.5       1   
2    18.0          8           318        150          11.0       1   
3    16.0          8           304        150          12.0       1   
4    17.0          8           302        140          10.5       1   
..    ...        ...           ...        ...           ...     ...   
193  24.0          6           200         81          17.6       1   
194  22.5          6           232         90          17.6       1   
195  29.0          4            85         52          22.2       1   
196  24.5          4            98         60          22.1       1   
197  29.0          4            90         70          14.2       2   

                           car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0    chevrolet chevelle malibu         NaN          NaN          NaN   
1  

In [75]:
# removing multiple columns
df.drop(columns=['displacement','horsepower'],inplace=True)
print(df)

     cylinders  acceleration                        car  Unnamed: 9  \
0            8          12.0  chevrolet chevelle malibu         NaN   
1            8          11.5          buick skylark 320         NaN   
2            8          11.0         plymouth satellite         NaN   
3            8          12.0              amc rebel sst         NaN   
4            8          10.5                ford torino         NaN   
..         ...           ...                        ...         ...   
193          6          17.6              ford maverick         NaN   
194          6          17.6                 amc hornet         NaN   
195          4          22.2         chevrolet chevette         NaN   
196          4          22.1            chevrolet woody         NaN   
197          4          14.2                  vw rabbit         NaN   

     Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  
0            NaN          NaN          NaN          NaN  
1            NaN          NaN  

In [76]:
print(df.isnull())

     cylinders  acceleration    car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0        False         False  False        True         True         True   
1        False         False  False        True         True         True   
2        False         False  False        True         True         True   
3        False         False  False        True         True         True   
4        False         False  False        True         True         True   
..         ...           ...    ...         ...          ...          ...   
193      False         False  False        True         True         True   
194      False         False  False        True         True         True   
195      False         False  False        True         True         True   
196      False         False  False        True         True         True   
197      False         False  False        True         True         True   

     Unnamed: 12  Unnamed: 13  
0           True         True  
1          

In [77]:
print(df.isnull().sum())

cylinders         0
acceleration      0
car               0
Unnamed: 9      198
Unnamed: 10     198
Unnamed: 11     198
Unnamed: 12     198
Unnamed: 13     198
dtype: int64


In [81]:
# Handling missing data 
df.dropna(axis=1,inplace=True)
print(df)

     cylinders  acceleration                        car
0            8          12.0  chevrolet chevelle malibu
1            8          11.5          buick skylark 320
2            8          11.0         plymouth satellite
3            8          12.0              amc rebel sst
4            8          10.5                ford torino
..         ...           ...                        ...
193          6          17.6              ford maverick
194          6          17.6                 amc hornet
195          4          22.2         chevrolet chevette
196          4          22.1            chevrolet woody
197          4          14.2                  vw rabbit

[198 rows x 3 columns]


In [83]:
df=pd.read_csv("D:/Ad_py_lib.csv/pandas_and_numpy/cars1.csv")

In [84]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0         1  chevrolet chevelle malibu         NaN          NaN          NaN   
1         1          buick skylark 320         NaN          NaN          NaN   
2         1         plymouth satellite         NaN          NaN          NaN   
3         1              amc rebel sst         NaN          NaN          NaN   
4         1                ford torino         NaN          NaN          NaN   
..      ...                        ...         ...          ...          ...   
193       1              ford maverick         NaN          NaN          NaN   
194       1                 amc hornet         NaN          NaN          NaN   
195       1         chevrolet chevette         NaN          NaN          NaN   
196       1            chevrolet woody         NaN          NaN          NaN   
197       2                  vw rabbit         NaN          NaN          NaN   

     Unnamed: 12  Unnamed: 13  
0            NaN          NaN  
1            NaN          NaN  
2            NaN          NaN  
3            NaN          NaN  
4            NaN          NaN  
..           ...          ...  
193          NaN          NaN  
194          NaN          NaN  
195          NaN          NaN  
196          NaN          NaN  
197          NaN          NaN  

[198 rows x 14 columns]

In [86]:
df.isnull().sum()

mpg               0
cylinders         0
displacement      0
horsepower        0
weight            0
acceleration      0
model             0
origin            0
car               0
Unnamed: 9      198
Unnamed: 10     198
Unnamed: 11     198
Unnamed: 12     198
Unnamed: 13     198
dtype: int64

In [88]:
df.fillna(0,inplace=True)
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  Unnamed: 9  Unnamed: 10

In [ ]:
df